site_name: Zeitplan Generator
repo_url: https://github.com/RcArtSolutions/TimetableGen
repo_name: GitHub
theme: amelia

pages:
- 'Einführung': 'index.md'
- 'Benutzung': 'user-guide.md'
- 'Über': 'about.md'
